# MAIN DOCKER COMPOSE

##############################
# NETWORKS
#
networks:
  default:
    name: home-automation
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.2.0/27
#
##############################

##############################
# VOLUMES
#
volumes:
  home-assistant-config:
    driver: local
    driver_opts:
      type: none
      device: ./home-assistant/config
      o: bind
#
##############################

##############################
# SECRETS (Non-Swarm)
#
secrets:
  zwave_secrets:
    file: ./secrets/hacs
#
##############################

##############################
# SERVICES
#
services:
  ##########
  # Home Assistant - 
  #
  home-assistant:
    image: ghcr.io/home-assistant/home-assistant:${HACS_TAG:-latest}
    container_name: home-assistant
    restart: always
    network_mode: host
    #networks:
    #  - default
    security_opt:
      - no-new-privileges:true    
    ports:
      - ${HACS_PORT:-8123}:8123/tcp
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:ro
      - home-assistant-config:/config
    environment:
      #DEBUG: "true"
      TZ: ${TZ}
  ##########
  #
  #################### 
#
##############################
